language: objective-c
osx_image: xcode7.2
env:
  matrix:
    - DESTINATION="OS=9.2,name=iPhone 6S Plus"  SCHEME="Pathology iOS"  SDK="iphonesimulator9.2"
    - DESTINATION="arch=x86_64"                 SCHEME="Pathology OSX"  SDK="macosx10.11"
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -project "Pathology.xcodeproj" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build test | xcpretty -c;
after_success:
  - bash <(curl -s https://codecov.io/bash)

